import streamlit as st

# Page configuration
st.set_page_config(
    page_title="🍏 Obesity Prediction App",
    page_icon="🍏",
    layout="centered",
    initial_sidebar_state="expanded",
)

# Adding the IE logo
st.image(
    "https://raw.githubusercontent.com/Bernardo-Santos23/MLII_Individual/main/images/iesst_logo.jpeg", 
    width=200, 
    caption="IE University - Master in Business Analytics & Big Data"
)

# Main title and small introduction
st.title("🍏 Welcome to the Obesity Prediction App")
st.write("""
Welcome to the **Obesity Prediction App**, your go-to tool for assessing the likelihood of obesity based on key health parameters.  
Navigate through the app using the **sidebar** to explore predictions, insights, and more.
""")

# Cover image generated by Dall-E to raise awarness
st.image(
    "https://raw.githubusercontent.com/Bernardo-Santos23/MLII_Individual/main/images/DallE-Doctor.webp", 
    width=500,
    caption="Generated by DALL-E: Promoting health awareness and improvement for obesity."
)

# Visual Divider
st.markdown("---")

# My name, section, course and teacher
st.markdown("""
### 👨‍💻 Created by  
**Bernardo Santos**  
*MBD - A-1 Spring 2025*  
*For Machine Learning II class, Prof. Concepción Díaz*
""")

# Motivational tagline (something extra)
st.markdown("""
### 🌟 Empowering Health Through Data  
Transforming health analytics into actionable insights.
""")

# Call-to-action for users
st.markdown("""
#### 📊 Start exploring the app now:  
1. Enter your health parameters.  
2. Get real-time obesity predictions.  
3. Understand the insights to take control of your health.  
""")
